#####################
#   连锁挖矿配置文件   #
#####################

# 是否启用
enabled: true

# 最大连锁方块数
max-active-num: 50

# 数据库设置
database:
  # 是否启用数据库
  enabled: false
  # 数据库类型（MySQL MongoDB SQLite）
  type: MySQL
  # 连接属性
  url: "jdbc:mysql://localhost:3306/mine_chain?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
  username: root
  password: 123456